# Generated by Django 5.2.6 on 2025-09-13 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number should be exactly 10 digits', regex='^\\d{10}$')])),
                ('state', models.CharField(default='Unknown', max_length=50)),
                ('city', models.CharField(default='Unknown', max_length=50)),
                ('crops', models.CharField(blank=True, default='Unknown', max_length=255)),
            ],
        ),
    ]
