# Generated by Django 5.2.6 on 2025-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=127)),
                ('soil_type', models.CharField(max_length=31)),
                ('description', models.TextField()),
                ('weather', models.CharField(max_length=255)),
                ('harvest_period', models.TextField()),
            ],
        ),
    ]
