# Generated by Django 5.2.6 on 2025-09-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='harvest_period',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='crops',
            name='soil_type',
            field=models.CharField(max_length=100),
        ),
    ]
